apiVersion:"sparkoperator.k8s.io/v1beta2"
kind:SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "tiagotxm/spark3.1:latest"
  imagePullPolicy: ifNotPresent
  mainApplicationFile: "s3://meu-bucket/spark_pi.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
