apiVersion:"sparkoperator.k8s.io/v1beta2"
kind:SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "tiagotxm/spark3.1:latest"
  imagePullPolicy: ifNotPresent
  mainApplicationFile: "s3://meu-bucket/spark_pi.py"
